name: PRIME-FIT underground
favicon: null
layout_spectrum: 0.98736
typography_spectrum: 0.75632
title: PRIME-FIT underground
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00adee'
    - '#fefefe'
    - '#2e3191'
    - '#000000'
    - '#7c7f82'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
