analytics: {}
color:
  brandColors:
    - '#00adee'
    - '#fefefe'
    - '#2e3191'
    - '#000000'
    - '#7c7f82'
  brandStrength: 0.405462
  lightness: 0.5
  rhythmicContrast: 0.25
  saturation: 0.5
cta: {}
layout_spectrum: 0.753151
name: PRIME-FIT underground
opengraph: {}
purpose: []
typography_spectrum: 0.75632
