layout_spectrum: 0.4192912148269317
typography_spectrum: 0.46728388303328344
color:
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  brandStrength: 0.11253336345039235
  lightness: 0.2573147955290641
  saturation: 0.46027862273958875
  rhythmicContrast: 0.5647412640645658
name: PRIME-FIT underground
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d650e0c-1700-48af-a8ad-f500010d1101.jpg
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Mail an Rene
    url: 'mailto:rbprivattraining@gmail.com'
  - type: contact
    label: Anruf Rene
    url: 'tel:+4915141268672'
title: die Top Seite für Insider
description: 'Medical Fitness, Ernährung, BB'
author:
  name: René Becker
  email: rbprivattraining@gmail.com
content_rating:
  adult: false
navigation:
  - name: "Ohne Mampf kein Kampf\uD83D\uDE02"
    id: 98f330b6-fc74-4c85-9681-33b4ef013718
    type: content
  - name: 'Westdeutsche NAC 2015 '
    id: ad613077-d219-4499-91d1-0af906f166a1
    type: content
  - name: 'Outdoor Aktivität '
    id: fc493170-c62c-47bb-9f82-ec859ef26733
    type: content
  - name: Supps für Ume
    id: 905408d4-8044-49d9-8b39-c7aebb94c4e5
    type: content
content: []
github: true
