name: PRIME-FIT underground
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d650e0c-1700-48af-a8ad-f500010d1101.jpg
layout_spectrum: 0.07147434762715925
typography_spectrum: 0.5990855768014962
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.08337466728495489
  lightness: 0.28618624528362835
  saturation: 0.24913162728411947
  rhythmicContrast: 0.9059370568764424
purpose:
  - type: contact
    label: Mail an Rene
    url: 'mailto:rbprivattraining@gmail.com'
title: die Top Seite für Insider
description: 'Medical Fitness, Ernährung, BB'
author:
  name: René Becker
  email: rbprivattraining@gmail.com
content_rating:
  adult: false
navigation:
  - name: "Ohne Mampf kein Kampf\uD83D\uDE02"
    id: 98f330b6-fc74-4c85-9681-33b4ef013718
    type: content
content: []
github: true
